### ISSUE TITLE
Ckeditor admin page incorrect button sizes

### ISSUE THREAD

**Issue by polnetwork** [thememachine/eleven#152]
# The issue is:
The buttons on the admin page appear to have a fixed width and do not show correctly
# Screenshots:
https://www.dropbox.com/s/gfksm2qtzcsr6se/Screenshot%202017-08-03%2013.26.00.png?dl=0
# Where (url)
admin/config/content/formats/manage/full_html

**Comment by mortendk** [comment]
![image](https://user-images.githubusercontent.com/65756/29094688-802f6b8c-7c8e-11e7-86a9-573b259f1526.png)
