### ISSUE TITLE
Message link needs more contrast

### ISSUE THREAD

**Issue by angelamnr** [thememachine/eleven#155]
# The issue is:
Message links don't have enough contrast with the message content background color.
Message background color is bluesky-light-light (#d1f1ff) and the link color is bluesky (#18a9e0). [WCAG contrast ](http://webaim.org/resources/contrastchecker/) for this is 2.28:1 when WCAG AA compliance requires 4.5:1.

# Screenshots:
http://i.imgur.com/dEu40P9.png

# Where (url)
admin/help is a page that has a message with links that don't have enough contrast.

Todo
- [ ] fix this
- [ ] fit that

**Comment by mortendk** [comment]
![image](https://user-images.githubusercontent.com/65756/29069453-5ac45bb2-7c3b-11e7-87ad-0a902cc71949.png)
