### ISSUE TITLE
Extend page (admin/modules) with module filter module: Form to large

### ISSUE THREAD

**Issue by drupalviking** [thememachine/eleven#176]
# The issue is:
Module form is too large and it slides under the Package list. Seems to be a problem with this markup: <form class="system-modules w-12 modules-tabs__pane"> (w-12 that is).

# Screenshots:
<img width="1304" alt="screen shot 2017-08-09 at 8 17 40 am" src="https://user-images.githubusercontent.com/7986212/29138558-17bf4534-7d12-11e7-8f69-d137ae4627ac.png">

# Where (url)
admin/modules

# Modules Installed:
module_filter

**Comment by mortendk** [comment]
sigh how i hate when classes are injected with js `modules-tabs__pane` 
the form wrapper gets a w-12  that messes with the with

**Comment by mortendk** [comment]
![image](https://user-images.githubusercontent.com/65756/29184665-3f0ee5ea-7e07-11e7-9f40-fe7189e7d263.png)
