### ISSUE TITLE
CKEditor Toolbar configuration

### ISSUE THREAD

**Issue by drupalviking** [thememachine/eleven#177]
# The issue is:
When configuring Toolbar for CKEditor, the buttons do not have enough space to display

# Screenshots:
<img width="1270" alt="screen shot 2017-08-09 at 9 40 40 am" src="https://user-images.githubusercontent.com/7986212/29138915-13e7c98a-7d13-11e7-97b5-190127b1f5df.png">

# Where (url)
/admin/config/content/formats/manage/basic_html

# Modules Installed:
Vanilla D8 Install

**Comment by mortendk** [comment]
update to beta2  and clear cache
