### ISSUE TITLE
6-column layout text issues

### ISSUE THREAD

**Issue by JAyenGreen** [thememachine/eleven#179]
# The issue is:
When switching the task view to 6 columns the task title text overflows (hidden/cropped) rather than wrapping or resizing
# Screenshots:
![screen shot 2017-08-09 at 7 37 14 pm](https://user-images.githubusercontent.com/1633477/29148301-524f35f6-7d21-11e7-8cf4-ad98b7c92a21.png)

# Where (url)
/admin
# Modules Installed:
If you _really_ need a list I'll add one

**Comment by mortendk** [comment]
![image](https://user-images.githubusercontent.com/65756/29187279-6fa026c6-7e0f-11e7-87fc-876f1dbea736.png)
