### ISSUE TITLE
Missing style information

### ISSUE THREAD

**Issue by larsmw** [thememachine/eleven#181]
# The issue is:
On some pages the admin menu in the top is missing style information.
# Screenshots:
![screenshot 2017-08-10 09-18-19](https://user-images.githubusercontent.com/1511277/29159023-76ea9d88-7dad-11e7-925b-6e87c7ea1ac6.png)

# Where (url)
admin/people, admin/appearance, admin/content
This seems random.

# Modules Installed:
lars@www2:~/sites/www.hjemmesideteknik.dk/public_html$ drush pml | grep Enabled
 Core          Automated Cron (automated_cron)     Module  Enabled        8.3.5 
 Core          Block (block)                       Module  Enabled        8.3.5 
 Core          Breakpoint (breakpoint)             Module  Enabled        8.3.5 
 Core          CKEditor (ckeditor)                 Module  Enabled        8.3.5 
 Core          Color (color)                       Module  Enabled        8.3.5 
 Core          Comment (comment)                   Module  Enabled        8.3.5 
 Core          Configuration Manager (config)      Module  Enabled        8.3.5 
 Core          Contact (contact)                   Module  Enabled        8.3.5 
 Core          Contextual Links (contextual)       Module  Enabled        8.3.5 
 Core          Custom Block (block_content)        Module  Enabled        8.3.5 
 Core          Custom Menu Links                   Module  Enabled        8.3.5 
 Core          Database Logging (dblog)            Module  Enabled        8.3.5 
 Core          Field (field)                       Module  Enabled        8.3.5 
 Core          Field UI (field_ui)                 Module  Enabled        8.3.5 
 Core          Filter (filter)                     Module  Enabled        8.3.5 
 Core          Help (help)                         Module  Enabled        8.3.5 
 Core          History (history)                   Module  Enabled        8.3.5 
 Core          Internal Dynamic Page Cache         Module  Enabled        8.3.5 
 Core          Internal Page Cache (page_cache)    Module  Enabled        8.3.5 
 Core          Menu UI (menu_ui)                   Module  Enabled        8.3.5 
 Core          Node (node)                         Module  Enabled        8.3.5 
 Core          Path (path)                         Module  Enabled        8.3.5 
 Core          Quick Edit (quickedit)              Module  Enabled        8.3.5 
 Core          RDF (rdf)                           Module  Enabled        8.3.5 
 Core          Search (search)                     Module  Enabled        8.3.5 
 Core          Shortcut (shortcut)                 Module  Enabled        8.3.5 
 Core          System (system)                     Module  Enabled        8.3.5 
 Core          Taxonomy (taxonomy)                 Module  Enabled        8.3.5 
 Core          Text Editor (editor)                Module  Enabled        8.3.5 
 Core          Toolbar (toolbar)                   Module  Enabled        8.3.5 
 Core          Tour (tour)                         Module  Enabled        8.3.5 
 Core          Update Manager (update)             Module  Enabled        8.3.5 
 Core          User (user)                         Module  Enabled        8.3.5 
 Core          Views (views)                       Module  Enabled        8.3.5 
 Core          Views UI (views_ui)                 Module  Enabled        8.3.5 
 Field types   Datetime (datetime)                 Module  Enabled        8.3.5 
 Field types   File (file)                         Module  Enabled        8.3.5 
 Field types   Image (image)                       Module  Enabled        8.3.5 
 Field types   Link (link)                         Module  Enabled        8.3.5 
 Field types   Options (options)                   Module  Enabled        8.3.5 
 Field types   Text (text)                         Module  Enabled        8.3.5 
 Fields        Field IP address (field_ipaddress)  Module  Enabled        8.3.5 
 Multilingual  Alternate hreflang (hreflang)       Module  Enabled        8.x-1 
 Multilingual  Interface Translation (locale)      Module  Enabled        8.3.5 
 Multilingual  Language (language)                 Module  Enabled        8.3.5 
 Other         Simple Social Buttons (socbutt)     Module  Enabled        8.x-1 
 Statistics    Google Analytics                    Module  Enabled        8.x-2 
 Anden         Eleven (eleven)                     Theme   Enabled        8.x-1 
 Core          Bartik (bartik)                     Theme   Enabled        8.3.5 
 Core          Seven (seven)                       Theme   Enabled        8.3.5 

Browser : Chromium v57

**Comment by mortendk** [comment]
Try the dev version: `drush up eleven-8.x-1.x-dev`

that made the issue go away for me
