### ISSUE TITLE
subtheme is not working

### ISSUE THREAD

**Issue by dunebaud** [thememachine/eleven#191]
# The issue is: I have followed this guide: https://www.drupal.org/docs/8/theming-drupal-8/creating-a-drupal-8-sub-theme-or-sub-theme-of-sub-theme for subtheming eleven.

To summarize, I have created only 3 files: eleven_sub.info.yml, eleven_sub.libraries.yml and style.css

# Screenshots:
![eleven_sub](https://user-images.githubusercontent.com/15786961/29195465-ebedc660-7e2e-11e7-9802-fd12f9fe3126.png)

Unfortunatly, when trying to use it, I got the following errors
`The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig_Error_Loader</em>: Template &quot;sites/lab06.be/themes/eleven_lab06/templates/component/navigation/cardlayout/cardlayout.html.twig&quot; is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template &quot;sites/lab06.be/themes/eleven_lab06/templates/component/navigation/cardlayout/cardlayout.html.twig&quot; in the Drupal theme registry.) in &quot;themes/contrib/eleven/eleven/templates/layout-landing/themes/system-themes-page.html.twig&quot; at line 8. in <em class="placeholder">Twig_Loader_Chain-&gt;getCacheKey()</em> (line <em class="placeholder">129</em> of <em class="placeholder">vendor/twig/twig/lib/Twig/Loader/Chain.php</em>). <pre class="backtrace">Drupal\Core\Template\TwigEnvironment-&gt;getTemplateClass(&#039;sites/lab06.be/themes/eleven_lab06/templates/component/navigation/cardlayout/cardlayout.html.twig&#039;) (Line: 419)
Twig_Environment-&gt;loadTemplate(&#039;sites/lab06.be/themes/eleven_lab06/templates/component/navigation/cardlayout/cardlayout.html.twig&#039;, NULL) (Line: 366)
Twig_Template-&gt;loadTemplate(&#039;sites/lab06.be/themes/eleven_lab06/templates/component/navigation/cardlayout/cardlayout.html.twig&#039;, &#039;themes/contrib/eleven/eleven/templates/layout-landing/themes/system-themes-page.html.twig&#039;, 8) (Line: 77)
__TwigTemplate_abedcdeda1ac799b7276decb240a18e489b46146d40f70c0cc222e6c97fd2cd1-&gt;doDisplay(Array, Array) (Line: 432)
Twig_Template-&gt;displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template-&gt;display(Array) (Line: 411)
Twig_Template-&gt;render(Array) (Line: 64)
twig_render_template(&#039;themes/contrib/eleven/eleven/templates/layout-landing/themes/system-themes-page.html.twig&#039;, Array) (Line: 384)
Drupal\Core\Theme\ThemeManager-&gt;render(&#039;system_themes_page&#039;, Array) (Line: 435)
Drupal\Core\Render\Renderer-&gt;doRender(Array) (Line: 448)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;Drupal\Core\Render\MainContent\{closure}() (Line: 574)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object) (Line: 108)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 158)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 656)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>`

As a workaround, I copied all the templates and favicons directories in my subtheme... But I feel that it is not the right way to do it.

**Comment by mortendk** [comment]
yeah theres an error with the include when its not done within the same folder 

inside of `themes/eleven/eleven/templates/layout-landing/themes/system-themes-page.html.twig`
is calling the cardlayout.html.twig template 
`{% include active_theme_path() ~ '/templates/component/navigation/cardlayout/cardlayout.html.twig' %}`

so i guess is the path for active_theme_path() that is messign with it

**Comment by mortendk** [comment]
Bam major this one goes to 12 
![image](https://user-images.githubusercontent.com/65756/29222338-59ce04ae-7ec2-11e7-9bc9-7601b3f6b164.png)


**/twelve/twelve.info.yml**
```
name: 12
type: theme
description: 'thise one goes to 12'
base theme: eleven #stable / classy
core: 8.x

```

**Comment by mortendk** [comment]
pushed to dev cause its friday and this is how i like to party
