### ISSUE TITLE
Minor A11Y markup issue

### ISSUE THREAD

**Issue by cehfisher** [thememachine/eleven#193]
# The issue is:
Avoid using `<b>` (bold) in markup. Assistive technologies and other browsers rely upon the literal markup of the page to determine structure. Items that are bolded or display in a bigger font are not interpreted to be structural elements.

# Where (url)
Ex. `Selected user` text on http://drupalvm-eleven.dev/admin/structure/contact

# How to fix:
Use a heading or class or even `<strong>` instead (depending on your intended use). See http://webaim.org/techniques/semanticstructure/ for more info on the subject.

**Comment by mortendk** [comment]
Woooop wooop no issue is to small and yes correct markup ... i took the lib to put it as a h5 just 
![image](https://user-images.githubusercontent.com/65756/29222587-57c92d2c-7ec3-11e7-8cbf-ffe5a29508f1.png)

**Comment by cehfisher** [comment]
oh no! you accidentally substituted one a11y issue for another...don't jump heading levels. you went from `<h3>` to `<h5>`. http://a11y-style-guide.com/style-guide/section-structure.html#kssref-structure-headings

close though :)

**Comment by mortendk** [comment]
USH goddammit see i knew i was doing somethinh wrong lol

**Comment by mortendk** [comment]
even that its friday night dont mean i should not do this prober 
![image](https://user-images.githubusercontent.com/65756/29224811-2469049e-7ecc-11e7-9efe-7de1a110b289.png)
