### ISSUE TITLE
Add aria-labels to section tags

### ISSUE THREAD

**Issue by widescreenBob** [thememachine/eleven#197]
# The issue is:
Sections / Articles are too generic. Assistive technology, such as screen readers, use the label attribute to catalog the objects in a document so that users can navigate between them.

# Screenshots: 
![developer_tools_-_httpdrupal8installadminstructurecontact_2017-08-11_12-05-14](https://user-images.githubusercontent.com/4236946/29222389-4842a564-7e90-11e7-8274-a8f925f9d646.png)

# Where (url): 
Globally where section article are used. Example /admin/structure

# How to fix:
 Use either 'aria-label' or 'aria-labelledby' to name the landmark in a way that clearly explains the purpose of the landmark to all users.
https://www.w3.org/TR/WCAG20-TECHS/ARIA20
[Aria Label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute)

# Example:
`<section  aria-label="Site Structure Elements"></section>`
`<article  aria-label="Block Layout"></article>`

@cehfisher

**Comment by mortendk** [comment]
there walked through all the table pages + card landing pages, should all be there now
