### ISSUE TITLE
webform Broken status message

### ISSUE THREAD

**Issue by beltofte** [thememachine/eleven#220]
# The issue is:
The status message looks weird on the modules pages. Looks like it happens due to the status message that Webform module outputs on the module page.

# Screenshots:
![eleventheme buggy](https://user-images.githubusercontent.com/108249/30051213-6d67cbd6-9221-11e7-9ee7-11eb61c73de3.png)

# Where (url)
- /admin/modules

# Modules Installed:
Webform

**Comment by mortendk** [comment]
thanx 👍
