### ISSUE TITLE
webform and promotions ...

### ISSUE THREAD

**Issue by jonasdk** [thememachine/eleven#221]
# The issue is:
i didnt ask for commercials 

# Screenshots:
![screen shot 2017-09-05 at 13 24 57](https://user-images.githubusercontent.com/85319/30059022-a276876a-923d-11e7-8972-3ca22995cb74.png)

![screen shot 2017-09-05 at 13 22 17](https://user-images.githubusercontent.com/85319/30058981-6c52487c-923d-11e7-9a91-f2621fd436f0.png)

# Where (url)
- /admin/structure/webform/addons

# Modules Installed:
webforms

**Comment by mortendk** [comment]
guess that a 
```
[class^='message--promotions']{
  display:none;
}```

can fix that noise :P

whats the real scandale here is offcourse the obscure cem hellish naming
its `message--promo-cause-were-like-mambo-wordpress` not `component--modifier__element`

**Comment by mortendk** [comment]
fixed other places :)
