### ISSUE TITLE
Tooltips Hover Effect

### ISSUE THREAD

**Issue by vulcanr** [thememachine/eleven#225]
# The issue is:
On any icon that has a tooltip help text, the text indentation is not properly placed, so when you mouseout from the icon, you can still see 1 or 2 first letters of that help text.
# Screenshots:
![tooltip hovers](https://user-images.githubusercontent.com/7149549/30912061-6777bfee-a38b-11e7-96c6-639611aadf11.gif)

# Where (url)
- /admin/*

# Modules Installed:
(just the important ones)

**Comment by mortendk** [comment]
![image](https://user-images.githubusercontent.com/65756/35554975-e7a6e50e-059d-11e8-9f39-b73e1953ead1.png)
 aka fixed

**Comment by vulcanr** [comment]
aka good to know :)

**Comment by mortendk** [comment]
yes were back on track but things have changed around my schedule ;)
