### ISSUE TITLE
Extra "}}>" in view of displaymodes. 

### ISSUE THREAD

**Issue by WebBeest** [thememachine/eleven#230]
# The issue is:
There's an extra "}}>" in the table-displaymodes.html.twig (line 27)

# Screenshots:
<img width="692" alt="screen shot 2017-09-29 at 10 30 40" src="https://user-images.githubusercontent.com/8982467/31007576-48fd47a6-a501-11e7-82fb-9735d8e1b8a2.png">

# Where (url)
- /admin/structure/display-modes/view

# Modules Installed:
Not important

**Comment by vulcanr** [comment]
I couldn't replicate this one

<img width="1530" alt="screen shot 2017-09-29 at 12 29 58" src="https://user-images.githubusercontent.com/7149549/31012399-f216cc3a-a511-11e7-98e5-cf820a52423a.png">

**Comment by dbazuin** [comment]
@WebBeest Dit you test this with the latest github version?

**Comment by WebBeest** [comment]
Nope. Installed this with composer require (1.0 beta3). 
Tested it with latest github version, no problems :)
