### ISSUE TITLE
Views filtering unreadable result. 

### ISSUE THREAD

**Issue by WebBeest** [thememachine/eleven#234]
# The issue is:
In the list of views the layout is unreadable when filtering on a view-name. 

# Screenshots:
<img width="661" alt="screen shot 2017-09-29 at 14 38 15" src="https://user-images.githubusercontent.com/8982467/31016176-fa68773c-a523-11e7-968c-3830173e85f2.png">

# Where (url)
- /admin/structure/views

# Modules Installed:
(just the important ones)

**Comment by mortendk** [comment]
cant recreate it
