### ISSUE TITLE
filter section is interfering with the clickable area of 'add product' button

### ISSUE THREAD

**Issue by shaal** [thememachine/eleven#238]
# The issue is:
The "Add Product" button is visible, but the clickable area of that button is mostly covered by the Toggle Filter section

# Screenshots:
(the black dashed box was not in the original screenshot and was added to emphasize the issue)
![image](https://user-images.githubusercontent.com/22901/31146437-bc4d455c-a854-11e7-8557-712c49d36c7d.png)

# Where (url)
- /admin/commerce/products

# Modules Installed:
Drupal Commerce

**Comment by mortendk** [comment]
there rewrote the flex box elements to use grid instead and cleaned up loads of code should be fixed now ;)
