### ISSUE TITLE
Coffee icon takes over the Workflow config page

### ISSUE THREAD

**Issue by jojototh** [thememachine/eleven#241]
# The issue is:
Coffee icon is not supposed to be there

# Screenshots:
![image](https://user-images.githubusercontent.com/710090/31183087-81c1c3f8-a91d-11e7-9443-744cd6f5b47f.png)

# Where (url)
- /admin/config/workflow/workflows/manage/editorial

# Modules Installed:
Content Moderation (D8 4-rc2 core experimental)

**Comment by mortendk** [comment]
![image](https://user-images.githubusercontent.com/65756/34542199-e0c81a5e-f0db-11e7-8788-bb5385da15c7.png)
