### ISSUE TITLE
HTML in admin boxes are autoescaped

### ISSUE THREAD

**Issue by holingpoon** [thememachine/eleven#243]
# The issue is: HTML tags are escaped within the help text on cards.

# Screenshots:
![image](http://www.holingpoon.com/html-render.png)

# Where (url)
- /admin/structure/types

# Modules Installed:

# Drupal Version
- 8.4.0

**Comment by holingpoon** [comment]
Possible related issues on drupal.org

- [Twig autoescape enabled and text sanitization APIs updated](https://www.drupal.org/node/2296163)
- [Turn on twig autoescape by default](https://www.drupal.org/node/1825952)
- [Fix HTML escaping due to Twig autoescape](https://www.drupal.org/node/2297711)

**Comment by holingpoon** [comment]
In the file `eleven/eleven/templates/layout-landing/config/admin-block.html.twig` I've tried `|raw` and `|escape` options in Twig but it did not work on my Drupal 8.4 instance. For example
`{{ block.description|escape }}` and `{{ block.description|raw }}` do not work.

**Comment by mortendk** [comment]
its hiding down in eleven/templates/layout-landing/contenttypes/table--structure-types.html.twig
