### ISSUE TITLE
node sidebar needs some love in mobile

### ISSUE THREAD

**Issue by Rar9** [thememachine/eleven#244]
# The issue is:

# Screenshots:

# Where (url)
- /admin/...

# Modules Installed:
(just the important ones)

**Comment by dbazuin** [comment]
@Rar9 Can you be more precise?
This is work in progress so it is very plausible that in some cases  things are not yet working as the should.

**Comment by Rar9** [comment]
![screenshot_20171009-075607](https://user-images.githubusercontent.com/2239608/31326445-a16cb200-acc7-11e7-9e49-8eaaa0abfecb.png)
![screenshot_20171009-075727](https://user-images.githubusercontent.com/2239608/31326448-a8008236-acc7-11e7-98f0-0cbe54c8e835.png)

It even gets worse in landscape. 

In addition the admin menue icons are too small and mobile unfriendly

**Comment by dbazuin** [comment]
Thanks for the feedback.

**Comment by dbazuin** [comment]
@Rar9 to be sure do you use the version from github to test or the latest from drupal.org/a/eleven ?

**Comment by Rar9** [comment]
Last from drupal, but will later switch to composer 

Am 9. Oktober 2017 08:09:16 MESZ schrieb Dirk Bazuin <notifications@github.com>:

**Comment by dbazuin** [comment]
Robert,

Can you instead of that just clone the version from github?

**Comment by holingpoon** [comment]
This is from Chrome 61.0.3163.98 on Samsung Galaxy S6 (Android 7.0.0; SM-G920V Build/NRD90M). Portrait orientation is off, but it is better behaved when the phone is rotated to landscape view.

Portrait view:
![image](https://user-images.githubusercontent.com/1801767/31390144-1660e1b0-ada1-11e7-86de-a16bc33f5c31.png)

Landscape view:
![image](https://user-images.githubusercontent.com/1801767/31390354-a8d4ce9e-ada1-11e7-8aa7-c969045cf399.png)

**Comment by mortendk** [comment]
❤️  added
