### ISSUE TITLE
Modal dialogues in Views unusable

### ISSUE THREAD

**Issue by iamnoskcaj** [thememachine/eleven#259]
# The issue is:
Modal dialogues in Views are unusable in Chrome and FF (latest builds).

# Screenshots:
![eleven-theme__views-modal](https://user-images.githubusercontent.com/171949/34690575-b45a5540-f487-11e7-963f-14514dc2a145.PNG)

# Where (url)
/admin/structure/views/view/[some-view-name]

# Modules Installed:
mostly core

**Comment by mortendk** [comment]
upsie looking at it

**Comment by mortendk** [comment]
"it works on my machine" ...
![image](https://user-images.githubusercontent.com/65756/34820184-18877018-f6c0-11e7-8094-85a779c4f70f.png)

did you pull the latest dev version ?

**Comment by iamnoskcaj** [comment]
Will try. Thanks.

**Comment by mortendk** [comment]
did it work ;)

**Comment by iamnoskcaj** [comment]
Just got back in the office. Will try shortly. Was away all weekend.
