### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by surindersinghva** [thememachine/eleven#260]
# The issue is: The 'Choose a File' button for a file field is not working. I had to switch the theme to upload files. I have tried everything, but the issue does exist. 

# Screenshots:
![file_field](https://user-images.githubusercontent.com/4016918/34708781-576aa528-f4e2-11e7-99ed-4fc3895facd7.PNG)

# Where (url)
- /admin/... add/edit content or taxonomy pages

# Modules Installed:
(just the important ones)

**Comment by mortendk** [comment]
confirmed and add it

**Comment by mortendk** [comment]
seven layout + functionality
![image](https://user-images.githubusercontent.com/65756/34768436-1a4848ac-f5fb-11e7-8a86-eafcae752430.png)

**Comment by mortendk** [comment]
the error was coursed by Drupal that uses the same id for the wrapper div as it uses for the form input :(

**Comment by mortendk** [comment]
and fixed  its in the next beta or grap the dev version

**Comment by surindersinghva** [comment]
Thank you so much! That was fast -:).

**Comment by mortendk** [comment]
:) no worries thanx for the bug report
