### ISSUE TITLE
Unable to filter content by type or status. There is no submit button. 

### ISSUE THREAD

**Issue by surindersinghva** [thememachine/eleven#268]
# The issue is:
I am unable to filter content by type or status on the /admin/content page. The submit button for that form is not showing up. 
# Screenshots:
![capture](https://user-images.githubusercontent.com/4016918/34879946-e2019bd2-f77c-11e7-99ca-d80fb11b3471.PNG)
# Where (url)
/admin/content

- /admin/...

# Modules Installed:
(just the important ones)

**Comment by mortendk** [comment]
check gonna fix it complete missed this as its overlap with the placement of the actions in the buttom of the page

**Comment by mortendk** [comment]
here we go also added as a bonus cards views on the content ;)
![image](https://user-images.githubusercontent.com/65756/35038108-f91d12d2-fb79-11e7-9169-479b50694a9a.png)

**Comment by surindersinghva** [comment]
Thanks a Million.

**Comment by surindersinghva** [comment]
Hmm... the issue still remains. Still cannot filter by Content Type or Status etc. Thank you for the Bonus cards, but they would make more sense if they were organized by Content Type. I am not an expert in this, but I would like to contribute if you want. Thank you for your efforts in the meantime,

**Comment by mortendk** [comment]
there it is 
![image](https://user-images.githubusercontent.com/65756/35113769-efef847e-fc82-11e7-956d-22219527192a.png)
