### ISSUE TITLE
Install problem - block.block.tabs

### ISSUE THREAD

**Issue by landsman** [thememachine/eleven#86]
Steps:
1. install via composer
2. go to admin -> click to "install" link => error message:

`Unable to install eleven, block.block.tabs already exists in active configuration.`

Installed profile: Thunder 2.0 - https://github.com/BurdaMagazinOrg/thunder-distribution

**Comment by amouro** [comment]
This issue is a conflict with the **Infinite theme** of Thunder distribution, which registered the block.block.tabs already.
After uninstall the **Infinite theme**, the Eleven theme can be installed without the error.

**Comment by landsman** [comment]
yeah, thats true

**Comment by mortendk** [comment]
#102  is merged hopefully that fixes the problem
